Develop (#2)
* Connect Wallet
Upload NFT and Metadata to IPFS
Mint NFT

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* use get...instead of use... because vercel
    Error: React Hook "usePOPR" is called in function "mintNft" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use".  react-hooks/rules-of-hooks

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* Remove toastify

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* Remove lock files.

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* Remove toastify import

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* removed unused file.

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* yarn lock

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* added environment file back.

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>

* Move environment file to utils.

Signed-off-by: Akintayo A. Olusegun <akintayo.segun@gmail.com>